In [9]:
#memasang pandas
import pandas as pd
pd.__version__

'3.0.2'

In [10]:
import pandas as pd

#A. Objek series pandas
#Membuat series sederhana(Contoh: Stok Produk)
data = pd.Series([10, 20, 30, 40, 50], index=['Produk A', 'Produk B', 'Produk C', 'Produk D', 'Produk E'])
data

Produk A    10
Produk B    20
Produk C    30
Produk D    40
Produk E    50
dtype: int64

In [11]:
data.values

array([10, 20, 30, 40, 50])

In [12]:
data.index

Index(['Produk A', 'Produk B', 'Produk C', 'Produk D', 'Produk E'], dtype='str')

In [13]:
data.iloc[3]

np.int64(40)

In [14]:
data[2:5]

Produk C    30
Produk D    40
Produk E    50
dtype: int64

In [15]:
#B. Series sebagai Array NumPy Umum
import pandas as pd
data = pd.Series([10, 20, 30, 40, 50], index=['Produk A', 'Produk B', 'Produk C', 'Produk D', 'Produk E'])
data

Produk A    10
Produk B    20
Produk C    30
Produk D    40
Produk E    50
dtype: int64

In [16]:
#C. Series sebagai dictionary khusus
import pandas as pd

#Membuat dictionary data ;uas wilayah(dalam ribuan km2)
Luas_dict = {
    'Indonesia': 1905,
    'Malaysia': 330,
    'Singapura': 0.7,
    'Thailand': 513,
    'Vietnam': 331
}

#mengonversi dictionary menjadi objek series pandas
Luas = pd.Series(Luas_dict)
Luas

Indonesia    1905.0
Malaysia      330.0
Singapura       0.7
Thailand      513.0
Vietnam       331.0
dtype: float64

In [17]:
#D. Mengakses item
Luas['Indonesia']

np.float64(1905.0)

In [18]:
#E. Slicing
Luas['Malaysia':'Thailand']

Malaysia     330.0
Singapura      0.7
Thailand     513.0
dtype: float64

In [19]:
#F. Membangun objek series
import numpy as np
import pandas as pd

pd.Series([5, 2, 1, 4, 1])

0    5
1    2
2    1
3    4
4    1
dtype: int64

In [20]:
pd.Series(4, index=[10, 15, 20])

10    4
15    4
20    4
dtype: int64

In [ ]:
pd.Series({15:'a', 20:'b', 25:'c'})
#Seharusnya ini object tapi ada anomali malah keluar datanya string(mungkin update di versi pandas 3 keatas)
#string seharusnya begini kalo object begini nanti gitu tulisnya di analisis

15    a
20    b
25    c
dtype: str

In [22]:
#A. DATAFRAME SEBAGAI ARRAY NUMPY UMUM
#Objek Dataframe Pandas
#Dataframe sbg array Numpy umum
import pandas as pd
import pandas as pd
luas_dict = {
    'Indonesia': 1905,
    'Malaysia': 330,
    'Singapura': 0.7,
    'Thailand': 513,
    'Vietnam': 331
}

luas = pd.Series(luas_dict)

penduduk_dict = {
    'Indonesia': 270,
    'Malaysia': 32,
    'Singapura': 5.7,
    'Thailand': 69,
    'Vietnam': 97
}
penduduk = pd.Series(penduduk_dict)
penduduk

Indonesia    270.0
Malaysia      32.0
Singapura      5.7
Thailand      69.0
Vietnam       97.0
dtype: float64

In [23]:
Negara = pd.DataFrame({
    'Luas': luas,
    'Penduduk': penduduk
})

Negara

             Luas  Penduduk
Indonesia  1905.0     270.0
Malaysia    330.0      32.0
Singapura     0.7       5.7
Thailand    513.0      69.0
Vietnam     331.0      97.0

In [24]:
Negara.index

Index(['Indonesia', 'Malaysia', 'Singapura', 'Thailand', 'Vietnam'], dtype='str')

In [25]:
Negara.columns

Index(['Luas', 'Penduduk'], dtype='str')

In [26]:
#B. DataFrame sebagai Dictionary Khusus
#Dataframe sebagai kamus khusus

Negara['Luas']

Indonesia    1905.0
Malaysia      330.0
Singapura       0.7
Thailand      513.0
Vietnam       331.0
Name: Luas, dtype: float64

In [27]:
#C. Membangun objek DataFrame
#1. Dari objek series tunggal
pd.DataFrame(luas, columns=['Luas'])

             Luas
Indonesia  1905.0
Malaysia    330.0
Singapura     0.7
Thailand    513.0
Vietnam     331.0

In [28]:
#2. Dari sebuah List dictionary
pd.DataFrame({'luas': luas, 'penduduk': penduduk})

             luas  penduduk
Indonesia  1905.0     270.0
Malaysia    330.0      32.0
Singapura     0.7       5.7
Thailand    513.0      69.0
Vietnam     331.0      97.0

In [30]:
#2 Daro array NumPy dua dimendi
pd.DataFrame(np.random.rand(5, 5),
             columns=['A', 'B', 'C', 'D', 'E'],
             index=['Baris 1', 'Baris 2', 'Baris 3', 'Baris 4', 'Baris 5'])

                A         B         C         D         E
Baris 1  0.186923  0.152077  0.387306  0.521567  0.035298
Baris 2  0.744442  0.694893  0.583791  0.900643  0.636603
Baris 3  0.032236  0.047615  0.992096  0.279228  0.848212
Baris 4  0.695842  0.968074  0.884313  0.474098  0.329202
Baris 5  0.472202  0.794759  0.903466  0.125025  0.330611

In [32]:
#4. Dari array terstrukk NumPy
A = np.zeros(3, dtype=[('Luas', 'f8'), ('Penduduk', 'f8')])

OBJEK INDEKS PANDAS

In [33]:
#A. Indeks sebagai array yang tidak berubah
#objek index pandas
ind = pd.Index([1, 2, 3, 4, 5])
ind

Index([1, 2, 3, 4, 5], dtype='int64')

In [34]:
ind[2]

np.int64(3)

In [35]:
ind[::3]

Index([1, 4], dtype='int64')

In [36]:
#objek index pandas
ind = pd.Index([1, 2, 3, 4, 5])
ind

Index([1, 2, 3, 4, 5], dtype='int64')

In [37]:
ind[3]=0

TypeError: Index does not support mutable operations

In [ ]:
#B. Indeks sebagai set yang dipesan
#indeks sebgai set yang dipesan
obj1 = pd.Index([1, 2, 3, 4, 5])

To Be Updated
As1 = Kamis jam 15:30
ACC = mingdepnya